# Generated by Django 3.2.4 on 2025-10-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skoulApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_user_email'),
        ),
    ]
