# Generated by Django 3.2.4 on 2025-10-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skoulApi', '0002_auto_20251007_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='Cours/'),
        ),
    ]
