# Generated by Django 3.2.4 on 2025-10-08 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skoulApi', '0003_alter_courses_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resulthomework',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
