# Generated by Django 3.2.4 on 2025-10-16 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skoulApi', '0004_alter_resulthomework_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='is_scheduled',
            field=models.BooleanField(default=False, help_text='Indique si le devoir est planifié pour un envoi différé'),
        ),
        migrations.AddField(
            model_name='homework',
            name='is_sent',
            field=models.BooleanField(default=False, help_text='Indique si le devoir a été envoyé aux étudiants'),
        ),
        migrations.AddField(
            model_name='homework',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, help_text="Date et heure d'envoi planifiée", null=True),
        ),
    ]
