# Generated by Django 3.2.4 on 2025-10-16 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skoulApi', '0005_auto_20251016_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Date et heure de fin de disponibilité du devoir', null=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='is_individual',
            field=models.BooleanField(default=False, help_text='Indique si le devoir est destiné à un étudiant spécifique'),
        ),
        migrations.AddField(
            model_name='homework',
            name='student',
            field=models.ForeignKey(blank=True, help_text='Étudiant spécifique (pour devoirs individuels, ex: étudiant malade)', limit_choices_to={'role': 'student'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
