# Generated by Django 3.2.4 on 2025-10-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skoulApi', '0006_auto_20251016_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='end_notification_sent',
            field=models.BooleanField(default=False, help_text='Indique si la notification de dépublication a été envoyée'),
        ),
    ]
